#!/usr/bin/env bun
/**
 * Tests for the repo-agnostic report kernel. Identity is INJECTED (the engine no
 * longer shells out to a repo's agent-identity script); the arc-side provenance
 * header + its agent-identity.sh integration are tested in
 * `.claude/verify/identity.test.ts`.
 */
import { describe, expect, test } from "bun:test";
import { type CheckResult, renderReport, run, sumNum, trimFullLogsSection } from "./report.ts";

const results: CheckResult[] = [
  {
    check: "build",
    title: "Build",
    pass: true,
    blocking: true,
    durationMs: 1234,
    stats: {},
  },
];

describe("renderReport", () => {
  test("injected identity string opens the report", () => {
    const identity = "> 🤖 AI Agent Verification @ host · runner:r · skills@abc";
    const md = renderReport(results, { scenario: "pre-pr", sha: "deadbeef123", identity });
    expect(md.split("\n")[0]).toBe(identity);
  });

  test("no identity → report opens directly with the heading (no blank leader)", () => {
    const md = renderReport(results, { scenario: "pre-pr" });
    expect(md.startsWith("## Verification Report")).toBe(true);
  });

  test("body content is intact: heading, table, overall", () => {
    const md = renderReport(results, { scenario: "pre-pr", base: "abcdef1234", sha: "deadbeef" });
    expect(md).toContain("## Verification Report");
    expect(md).toContain("| Build | ✅ PASS |");
    expect(md).toContain("**Overall: ✅ PASS**");
  });

  test("a blocking failure flips Overall to FAIL and renders a Failures block", () => {
    const failing: CheckResult[] = [
      {
        check: "types",
        title: "Types",
        pass: false,
        blocking: true,
        durationMs: 10,
        stats: { errors: 3 },
        rawTail: "TS2345: bad",
      },
    ];
    const md = renderReport(failing, { scenario: "pre-pr" });
    expect(md).toContain("**Overall: ❌ FAIL**");
    expect(md).toContain("### Failures");
    expect(md).toContain("TS2345: bad");
  });

  test("a warn-only (non-blocking) failure keeps Overall PASS", () => {
    const warn: CheckResult[] = [
      {
        check: "format",
        title: "Format",
        pass: false,
        blocking: false,
        durationMs: 5,
        stats: {},
      },
    ];
    const md = renderReport(warn, { scenario: "pre-pr" });
    expect(md).toContain("**Overall: ✅ PASS**");
    expect(md).toContain("⚠️ WARN");
  });
});

describe("trimFullLogsSection (#1922 — comment-filter work-budget retry)", () => {
  test("strips the Full Logs appendix, keeping the summary table and a note", () => {
    const results: CheckResult[] = [
      {
        check: "build",
        title: "Build",
        pass: true,
        blocking: true,
        durationMs: 1000,
        stats: {},
        rawFull: "a".repeat(100),
      },
    ];
    const md = renderReport(results, { scenario: "pre-pr", sha: "deadbeef123" });
    expect(md).toContain("### Full Logs");
    expect(md).toContain("<details>");

    const trimmed = trimFullLogsSection(md);
    expect(trimmed).toContain("## Verification Report");
    expect(trimmed).toContain("**Overall: ✅ PASS**");
    expect(trimmed).toContain("### Full Logs");
    expect(trimmed).not.toContain("<details>");
    expect(trimmed).toContain("Omitted");
    // The trailing generated-by line survives the trim (plugin's de-arc-ified text).
    expect(trimmed).toContain("Generated by the `agentloop` verification engine");
  });

  test("is a no-op when the report has no Full Logs section", () => {
    const results: CheckResult[] = [
      { check: "build", title: "Build", pass: true, blocking: true, durationMs: 1000, stats: {} },
    ];
    const md = renderReport(results, { scenario: "pre-pr" });
    expect(md).not.toContain("### Full Logs");
    expect(trimFullLogsSection(md)).toBe(md);
  });
});

// Ported from main's verification/scripts/report.test.ts on merge (#1922/#2054): the run() subprocess
// timeout landed in report.ts via auto-merge; its test lives here now that the engine is in the plugin.
describe("sumNum (arc#2080 — check-tests must total per-task summaries, not grab the first)", () => {
  test("sums every match instead of returning only the first", () => {
    // Real shape: turbo runs test tasks concurrently and interleaves each
    // package's own bun-test summary line into one combined stdout.
    const out = [
      "@aigne/afs-aup:test:  12 pass",
      "@aigne/afs-aup:test:  0 fail",
      "@aigne/aos:test:  1147 pass",
      "@aigne/aos:test:  0 fail",
      "@aigne/afs-integration-tests:test:  1353 pass",
      "@aigne/afs-integration-tests:test:  0 fail",
    ].join("\n");
    expect(sumNum(/(\d+) pass(?=\s*(?:\/|$|\n))/gim, out)).toBe(12 + 1147 + 1353);
    expect(sumNum(/(\d+) fail(?=\s*(?:\/|$|\n))/gim, out)).toBe(0);
  });

  test("handles the combined 'N pass / N fail / N skip' single-line summary shape too", () => {
    const out = "@aigne/afs-ui:test: 7283 pass / 0 fail / 15 skip";
    expect(sumNum(/(\d+) pass(?=\s*(?:\/|$|\n))/gim, out)).toBe(7283);
    expect(sumNum(/(\d+) fail(?=\s*(?:\/|$|\n))/gim, out)).toBe(0);
  });

  test("does not false-positive on digit+'fail'/'pass' phrases inside test NAMES (arc#2080, real captured cases)", () => {
    // Real lines pulled from an actual affected-tests run: "P3 fail-closed" and
    // "T5.1 fail-loud" are describe-block labels, not bun-test summary lines —
    // a naive `\d+ fail` match previously reported these as real failures
    // (passed=1147 / failed=3 was actually a fully-green run, code===0).
    const out = [
      "@aigne/arc-worker:test: (pass) exec /.actions/write {path:/user/...} → REJECTED (P3 fail-closed, write does not leak) [1.2ms]",
      "@aigne/arc-worker:test: (pass) deriveInstallerDid (T5.1 fail-loud) > derives a normalized did [0.5ms]",
      "@aigne/arc-worker:test: (pass) deriveInstallerDid (T5.1 fail-loud) > is deterministic [0.3ms]",
      "@aigne/arc-worker:test: (pass) deriveInstallerDid (T5.1 fail-loud) > throws on empty input [0.4ms]",
      "@aigne/arc-worker:test:  4 pass",
      "@aigne/arc-worker:test:  0 fail",
    ].join("\n");
    expect(sumNum(/(\d+) fail(?=\s*(?:\/|$|\n))/gim, out)).toBe(0);
    expect(sumNum(/(\d+) pass(?=\s*(?:\/|$|\n))/gim, out)).toBe(4);
  });

  test("returns undefined when there are no matches", () => {
    expect(sumNum(/(\d+) pass(?=\s*(?:\/|$|\n))/gim, "no test output here")).toBeUndefined();
  });
});

describe("run() timeoutMs (#2054 — a stuck subprocess must not hang pre-pr.ts forever)", () => {
  test("kills a hung command at timeoutMs and reports code 124 + timedOut:true", () => {
    const start = Date.now();
    const r = run("sleep 999", {}, undefined, 300);
    const elapsed = Date.now() - start;
    expect(r.code).toBe(124);
    expect(r.timedOut).toBe(true);
    // Must return promptly after the timeout, not after the full 999s sleep.
    expect(elapsed).toBeLessThan(10_000);
  });

  test("without timeoutMs, behavior is unchanged — real exit code, no timedOut flag", () => {
    const r = run("exit 3");
    expect(r.code).toBe(3);
    expect(r.timedOut).toBeUndefined();
  });

  test("a fast command under a generous timeoutMs completes normally", () => {
    const r = run("echo hi", {}, undefined, 5000);
    expect(r.code).toBe(0);
    expect(r.out.trim()).toBe("hi");
    expect(r.timedOut).toBeUndefined();
  });
});
