#!/usr/bin/env bun
import { describe, expect, it } from "bun:test";
/**
 * L1 golden-scenario evals for issue-sweep Step 2 filter logic.
 *
 * Covers 6 historical cases (all fixtures in ./fixtures/) and the pure TS
 * predicates in lib.ts — hermetic, no LLM, no network.
 *
 * References:
 *   ArcBlock/arc#1207 — L1 golden-scenario eval harness acceptance criteria
 *   ArcBlock/arc#1211 — L0/L1/L2/L3 framework discussion
 *   .claude/plugins/agentloop/skills/issue-sweep/SKILL.md Step 2
 */
import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import {
  type Comment,
  extractSweepTraces,
  type Issue,
  isAiAgentComment,
  isNonTerminalAiComment,
  isTerminalAiComment,
  isTestSweepFinding,
  labelStance,
  shouldProcess,
} from "./lib.ts";

// ---------------------------------------------------------------------------
// Fixture schema (mirrors the JSON shape)
// ---------------------------------------------------------------------------
interface Fixture {
  _comment?: string;
  issue: {
    number: number;
    labels?: string[];
    body?: string;
    comments?: Array<{ body: string; created_at?: string }>;
  };
  expected: {
    step2_keep: boolean;
    reason: string;
  };
  forbidden_actions: string[];
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function fixtureToIssue(f: Fixture): Issue {
  return {
    number: f.issue.number,
    labels: f.issue.labels,
    body: f.issue.body,
    comments: (f.issue.comments ?? []) as Comment[],
  };
}

async function loadFixtures(): Promise<Array<{ name: string; fixture: Fixture }>> {
  const dir = join(import.meta.dir, "fixtures");
  const files = (await readdir(dir)).filter((f) => f.endsWith(".json"));
  return Promise.all(
    files.map(async (name) => ({
      name,
      fixture: JSON.parse(await readFile(join(dir, name), "utf8")) as Fixture,
    })),
  );
}

describe("unattended orchestration contract", () => {
  it("allows bounded non-interactive issue fan-out while retaining a serial fallback", async () => {
    const skill = await readFile(join(import.meta.dir, "..", "..", "SKILL.md"), "utf8");
    const prompt = await readFile(
      join(import.meta.dir, "..", "..", "..", "..", "fleet", "prompts", "issue-sweep.md"),
      "utf8",
    );
    const issueReview = await readFile(
      join(import.meta.dir, "..", "..", "..", "issue-review", "SKILL.md"),
      "utf8",
    );

    expect(skill).toContain('skillConcurrency["issue-sweep"]');
    expect(skill).toContain("主控分配,worker 即时 claim");
    expect(skill).toContain("不预加");
    expect(skill).toContain("会改 repo 的 worker 必须使用独立 worktree");
    expect(skill).toContain("AGENTLOOP_SETUP_COMMAND");
    expect(skill).toContain("共享 KB 由主控单写,worker 仍贡献 KB");
    expect(skill).toContain("绝不代删");
    expect(skill).toContain("嵌套 fan-out 也受 runtime 总 slot 限制");
    expect(skill).toContain("没有非交互 agent 能力时");
    expect(skill).not.toContain("编排一律串行 inline");
    expect(skill).not.toContain("主控先 claim");

    expect(prompt).toContain("The prohibition is on interactive orchestration, not parallelism");
    expect(prompt).toContain('skillConcurrency["issue-sweep"]');
    expect(prompt).toContain("--concurrency {{CONCURRENCY}}");
    expect(prompt).toContain("arguments `--autofix-green --concurrency {{CONCURRENCY}}`");
    expect(prompt).toContain("bounded worker-pool contract");
    expect(prompt).toContain("fall back to serial inline only when it does not");
    expect(prompt).not.toContain("Orchestrate serially inline");

    expect(issueReview).toContain("不替 worker 预加锁");
    expect(issueReview).toContain("把结构化 KB delta 返回主控统一折叠");
    expect(issueReview).not.toContain("串行 inline + 待拍板问题落 comment");
  });
});

// ---------------------------------------------------------------------------
// isAiAgentComment
// ---------------------------------------------------------------------------
// A realistic autonomous verdict carries a sweep-trace (SKILL.md §sweep-trace mandates it).
const TRACE =
  '\n<!-- sweep-trace: {"ver":1,"issue":1,"gate":"disposition","val":"x","run":"2026-07-01T00:00:00Z","runner":"r","skills":"h"} -->';

describe("isAiAgentComment (marker-based: a machine sweep-trace, not the copyable 🤖 header)", () => {
  it("a real sweep verdict (carries a sweep-trace) is agent — any opener form", () => {
    expect(isAiAgentComment(`> 🤖 AI Agent — issue-sweep\nbody${TRACE}`)).toBe(true);
    expect(isAiAgentComment(`## 🤖 pr-review\n\nverdict${TRACE}`)).toBe(true);
    expect(isAiAgentComment(`@ vm\n\n> 🤖 AI Agent — pr-sweep\nbody${TRACE}`)).toBe(true);
  });

  it("the `_Generated by [Claude Code]` footer also marks a comment agent-authored", () => {
    expect(isAiAgentComment("verdict text\n\n_Generated by [Claude Code]_")).toBe(true);
  });

  it("an HTML-ESCAPED sweep-trace still counts (#1278 double-escape, seen live)", () => {
    expect(isAiAgentComment('verdict\n\n&lt;!-- sweep-trace: {"ver":1} --&gt;')).toBe(true);
  });

  // THE arc#1722 REGRESSION: a HUMAN posting locally via scripts/agent-identity.sh produces
  // the identical `> 🤖 AI Agent @ host · runner:… · skills@…` header. Header-detection read
  // this human Phase-4 directive as an agent verdict and skipped the issue for 19h. With no
  // sweep-trace, it must be HUMAN → the sweep responds.
  it("a HUMAN comment using the 🤖 identity header (no trace) is NOT agent", () => {
    expect(
      isAiAgentComment(
        "> 🤖 AI Agent @ wangshijun-mac-studio · runner:wangshijun · skills@abc-dirty\n\n# Phase 4 plan\n…",
      ),
    ).toBe(false);
  });

  it("the presence-board `> 📡` heartbeat stays non-human even without a trace (#1361)", () => {
    expect(isAiAgentComment("> 📡 presence heartbeat — issue-sweep hourly · no-op")).toBe(true);
  });

  it("plain human comments are not agent", () => {
    expect(isAiAgentComment("LGTM on the proposed fix.")).toBe(false);
    expect(isAiAgentComment("这个我看了,按方案 B 来吧。")).toBe(false);
    expect(isAiAgentComment("I asked the 🤖 AI Agent to fix this")).toBe(false);
    expect(isAiAgentComment("")).toBe(false);
  });
});

describe("labelStance (arc#1722: which of agent:ready / needs-human-confirm was applied last)", () => {
  const ev = (label: string, at: string, action: "labeled" | "unlabeled" = "labeled") => ({
    label,
    action,
    at,
  });
  it("agent:ready applied AFTER needs-human-confirm → work it", () => {
    expect(
      labelStance([
        ev("needs-human-confirm", "2026-07-16T10:00:00Z"),
        ev("agent:ready", "2026-07-17T09:00:00Z"),
      ]),
    ).toBe("work");
  });
  it("needs-human-confirm applied AFTER agent:ready → wait", () => {
    expect(
      labelStance([
        ev("agent:ready", "2026-07-16T10:00:00Z"),
        ev("needs-human-confirm", "2026-07-17T09:00:00Z"),
      ]),
    ).toBe("wait");
  });
  it("only agent:ready → work; only needs-human-confirm → wait; neither → unknown", () => {
    expect(labelStance([ev("agent:ready", "2026-07-16T10:00:00Z")])).toBe("work");
    expect(labelStance([ev("needs-human-confirm", "2026-07-16T10:00:00Z")])).toBe("wait");
    expect(labelStance([ev("P1", "2026-07-16T10:00:00Z")])).toBe("unknown");
  });
  it("a later `unlabeled` clears the label (removed → not counted)", () => {
    expect(
      labelStance([
        ev("agent:ready", "2026-07-16T10:00:00Z"),
        ev("needs-human-confirm", "2026-07-17T09:00:00Z"),
        ev("needs-human-confirm", "2026-07-17T12:00:00Z", "unlabeled"),
      ]),
    ).toBe("work"); // confirm was removed → only ready stands
  });

  // #1831 盲区一:verification-report / e2e-gate 的 HTML 标记必须在正文最前
  // (merge-gate.ts 解析需要),导致 startswith 判据把机器评论误判为人类
  it("recognizes AI comment behind a leading verification-report HTML marker (#1831)", () => {
    expect(
      isAiAgentComment(
        "<!-- verification-report sha=e408e83e1f2a3b4c result=NA -->\n> 🤖 AI Agent Verification @ vm · runner:yechao · skills@e408e83\nreport body",
      ),
    ).toBe(true);
  });

  it("recognizes AI comment behind multiple leading HTML markers (#1831)", () => {
    expect(
      isAiAgentComment(
        '<!-- pr-review-verdict -->\n<!-- sweep-trace: {"ver":1,"pr":1,"gate":"verdict","val":"MERGE","run":"2026-07-17T00:00:00Z"} -->\n> 🤖 AI Agent PR Review @ vm · runner:robert · skills@abc\nverdict',
      ),
    ).toBe(true);
  });

  it("does NOT treat a human comment with a leading HTML marker as AI (#1831)", () => {
    expect(isAiAgentComment("<!-- note-to-self -->\nLGTM, merging this manually.")).toBe(false);
  });

  // #1822 实踩变种 1:MCP double-HTML-encode(#1278)把 marker 变成 &lt;!-- ... --&gt;
  it("recognizes AI comment behind an HTML-entity-escaped marker (#1831/#1278)", () => {
    expect(
      isAiAgentComment(
        "&lt;!-- verification-report sha=e408e83e result=NA --&gt;\n> 🤖 AI Agent Verification @ vm · runner:yechao · skills@e408e83",
      ),
    ).toBe(true);
  });

  // #1822 实踩变种 2:$(cat ...) 未展开的事故评论(#1298 同款),唯一机器信号是
  // Claude Code 自动附加的行首签名
  it("recognizes broken agent comment via Claude Code trailer at line start (#1831/#1298)", () => {
    expect(
      isAiAgentComment(
        "$(cat /tmp/claude-0/scratchpad/pm-final.md)\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_",
      ),
    ).toBe(true);
  });

  it("does NOT treat a human reply quoting an AI comment (with quoted trailer) as AI (#1831)", () => {
    expect(
      isAiAgentComment(
        "please fix the second case too\n\n> 🤖 AI Agent PR Review @ vm\n> some quoted verdict\n> _Generated by [Claude Code](https://claude.ai/code)_",
      ),
    ).toBe(false);
  });

  // arc#1362 archetype: the presence-board heartbeat is script-authored
  // (scripts/presence-heartbeat.ts edits the same comment in place) but carries
  // no sweep-trace and no `> 🤖 AI Agent` marker — without this exception it
  // reads as a fresh human reply and the board gets "re-processed" every round.
  it("recognizes the presence-board `> 📡` heartbeat as non-human (#1361/#1362)", () => {
    expect(
      isAiAgentComment(
        '<!-- presence: {"runner":"Robert Mao"} -->\n> 📡 **runner: Robert Mao** — 由 `scripts/presence-heartbeat.ts` 维护(编辑本 comment,不新发)\n\n| routine | last beat |...',
      ),
    ).toBe(true);
  });

  // arc#1977 archetype: not just the leading HTML comment but the `> 🤖` marker
  // LINE ITSELF arrived double-HTML-encoded (`&gt;` instead of `>`), so the
  // #1278 leading-comment decode alone wasn't enough to recognize it.
  it("recognizes AI comment when the marker line itself is double-HTML-escaped (#1278 variant, arc#1977)", () => {
    expect(
      isAiAgentComment(
        "&lt;!-- test-sweep-report --&gt;\n&gt; 🤖 AI Agent @ vm · runner:yechao · skills@71a1c3c1\n\nreport body",
      ),
    ).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// isNonTerminalAiComment
// ---------------------------------------------------------------------------
describe("isNonTerminalAiComment", () => {
  it("detects '不在本轮范围 / 留开放' pattern (#533 archetype)", () => {
    expect(
      isNonTerminalAiComment(
        "> 🤖 AI Agent — issue-sweep 2026-05-20\n🟠 不在本轮范围 / 留开放：需要架构决策。",
      ),
    ).toBe(true);
  });

  it("detects 'candidate-queued' english alias", () => {
    expect(isNonTerminalAiComment("> 🤖 AI Agent\ncandidate-queued for next run")).toBe(true);
  });

  it("detects 'queued' pattern", () => {
    expect(isNonTerminalAiComment("> 🤖 AI Agent\nThis is queued for the next sweep.")).toBe(true);
  });

  it("detects 'in-progress' continuation marker", () => {
    expect(
      isNonTerminalAiComment(
        "> 🤖 AI Agent — issue-sweep 2026-06-01\nin-progress: phase 2 pending",
      ),
    ).toBe(true);
  });

  it("detects '排队' pattern", () => {
    expect(isNonTerminalAiComment("> 🤖 AI Agent\n🟡 排队中，下轮处理。")).toBe(true);
  });

  it("detects '本轮未做' pattern", () => {
    expect(isNonTerminalAiComment("> 🤖 AI Agent\n本轮未做，稍后继续。")).toBe(true);
  });

  it("returns false for terminal PR-linked comment", () => {
    expect(isNonTerminalAiComment("> 🤖 AI Agent\n已完成，见 PR #538。")).toBe(false);
  });

  it("returns false for needs-human-confirm verdict", () => {
    expect(isNonTerminalAiComment("> 🤖 AI Agent\n安全敏感，needs-human-confirm。")).toBe(false);
  });

  it("returns false for a terminal 'needs-design' verdict", () => {
    expect(isNonTerminalAiComment("> 🤖 AI Agent\nneeds-design: A-vs-B decision required")).toBe(
      false,
    );
  });
});

// ---------------------------------------------------------------------------
// isTerminalAiComment
// ---------------------------------------------------------------------------
describe("isTerminalAiComment", () => {
  it("terminal when comment links a PR", () => {
    expect(isTerminalAiComment("> 🤖 AI Agent\n修复已提交，见 PR #540。")).toBe(true);
  });

  it("terminal when comment says needs-human-confirm", () => {
    expect(isTerminalAiComment("> 🤖 AI Agent\nneeds-human-confirm: 需要 A-vs-B 决策。")).toBe(
      true,
    );
  });

  it("NOT terminal when comment says 留开放 and has no real unlock condition", () => {
    expect(isTerminalAiComment("> 🤖 AI Agent\n🟠 不在本轮范围 / 留开放，PR 暂无计划。")).toBe(
      false,
    );
  });

  // TERMINAL WINS (SKILL.md Step 2, detection step 2): a genuine unlock
  // condition overrides an incidental deferral-looking word elsewhere in the
  // same comment. Before this fix, isNonTerminalAiComment checked
  // NON_TERMINAL_PATTERNS unconditionally and never looked at
  // TERMINAL_INDICATORS at all, so a comment with a real `needs-human-confirm`
  // verdict got silently re-classified as "unfinished" whenever it also
  // happened to contain any deferral-looking substring.
  it("TERMINAL WINS: a real needs-human-confirm verdict overrides an incidental 'todo' substring (arc#1923 archetype)", () => {
    const body =
      "> 🤖 AI Agent Issue Review\n" +
      "A2(did-space authed `/explorer` 走查)和 B(todo 宿主 + 嵌入 explorer 走查)不受这个虚假前提影响,可以独立往前推。\n" +
      '<!-- sweep-trace: {"ver":1,"issue":1923,"gate":"disposition","val":"needs-human-confirm","run":"2026-07-19T02:30:00Z"} -->';
    expect(isNonTerminalAiComment(body)).toBe(false);
    expect(isTerminalAiComment(body)).toBe(true);
  });

  // arc#1983 archetype: "这没有核实，不在本轮范围内" is a scoping caveat about
  // what wasn't checked, not a deferral of the whole comment — and the same
  // comment already carries a genuine `needs-human-confirm` verdict.
  it("TERMINAL WINS: a scoping caveat containing '不在本轮' does not mask a real needs-human-confirm verdict (arc#1983 archetype)", () => {
    const body =
      "> 🤖 AI Agent\n" +
      "这部分(iOS 具体到 module 级别还是仅 stub)没有核实，不在本轮范围内，仅指出「已有代码可读」这一事实。\n" +
      "标签（`research` + `needs-human-confirm`）已正确，本 issue 保持 parked，等待拍板。";
    expect(isNonTerminalAiComment(body)).toBe(false);
    expect(isTerminalAiComment(body)).toBe(true);
  });

  // The code-span stripping (step 1) still protects the ORIGINAL documented
  // incident — a YAML key inside a fenced code block must not trip the
  // deferral pattern — when there is no competing terminal indicator either.
  it("still ignores a deferral-looking word inside a fenced code block when no terminal indicator is present", () => {
    const body = "> 🤖 AI Agent\n配置示例:\n```yaml\ncancel-in-progress: false\n```\n仅供参考。";
    expect(isNonTerminalAiComment(body)).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// shouldProcess — inline unit cases
// ---------------------------------------------------------------------------
describe("shouldProcess — inline", () => {
  it("zero-comment issue with plain body → keep (unprocessed)", () => {
    const issue: Issue = {
      number: 1,
      comments: [],
      body: "Please fix the flaky login test.",
    };
    expect(shouldProcess(issue)).toBe(true);
  });

  it("zero-comment issue whose body IS an agent comment → skip", () => {
    // This edge case: spin-off body starts with > 🤖 but that's a spin-off author quoting
    // — body of an issue is never actually an agent comment in practice,
    // but we test the predicate logic directly
    const issue: Issue = {
      number: 2,
      comments: [],
      body: "> 🤖 AI Agent — auto-generated spin-off\nDelete sample.test.ts" + TRACE,
    };
    // Body itself IS an AI agent comment → treated as "already processed" → skip
    expect(shouldProcess(issue)).toBe(false);
  });

  it("last comment is human → keep", () => {
    const issue: Issue = {
      number: 3,
      comments: [
        { body: "> 🤖 AI Agent — sweep\nAudit note." + TRACE },
        { body: "I've confirmed the bug in staging. LGTM." },
      ],
    };
    expect(shouldProcess(issue)).toBe(true);
  });

  it("last comment is terminal AI → skip", () => {
    const issue: Issue = {
      number: 4,
      comments: [
        { body: "Confirmed." },
        { body: "> 🤖 AI Agent — sweep\nFix delivered in PR #99. Closing." + TRACE },
      ],
    };
    expect(shouldProcess(issue)).toBe(false);
  });

  it("last comment is non-terminal AI (deferred) → keep and re-process", () => {
    const issue: Issue = {
      number: 5,
      comments: [
        { body: "Good idea." },
        { body: "> 🤖 AI Agent — sweep 2026-05-20\n🟠 不在本轮范围 / 留开放。" + TRACE },
      ],
    };
    expect(shouldProcess(issue)).toBe(true);
  });

  it("single AI-audit-only comment → skip (terminal audit, no human reply)", () => {
    const issue: Issue = {
      number: 6,
      comments: [
        { body: "> 🤖 AI Agent — doc-audit\nDocument is drifted. needs-human-confirm." + TRACE },
      ],
    };
    expect(shouldProcess(issue)).toBe(false);
  });

  // #2271 archetype: test-sweep opens per-blocklet failure issues directly (not through
  // issue-publish's test-sweep-key marker path), so the body carries the `> 🤖 AI Agent`
  // identity header but no MACHINE_MARKER. Before the label-aware fix this was a false
  // positive: shouldProcess() read a zero-comment automated QA finding as an unprocessed
  // human directive. See SKILL.md Step 3b "test-sweep 发现的 issue".
  it("zero-comment test-sweep-failure issue → skip (automated QA finding, not human input)", () => {
    const issue: Issue = {
      number: 2271,
      labels: ["P2", "test-sweep-failure"],
      comments: [],
      body: "test-sweep 失败报告...\n\n> 🤖 AI Agent @ vm · runner:yechao · skills@56f6c81c",
    };
    expect(shouldProcess(issue)).toBe(false);
  });

  it("zero-comment test-sweep-report (parent QA report) → skip, same rule", () => {
    const issue: Issue = {
      number: 2274,
      labels: ["test-sweep-report"],
      comments: [],
      body: "[test-sweep] QA Report — 2026-07-22 20:08 UTC\n\n> 🤖 AI Agent @ vm · runner:yechao · skills@56f6c81c",
    };
    expect(shouldProcess(issue)).toBe(false);
  });

  it("a test-sweep-failure issue that LATER gets a real human reply is still kept normally", () => {
    // Once a human actually comments, the ordinary last-comment rule takes back over —
    // the label-based override only applies to the zero-comment gap.
    const issue: Issue = {
      number: 2271,
      labels: ["P2", "test-sweep-failure"],
      comments: [{ body: "这个登录墙是有意的,不是回归,可以关闭。" }],
    };
    expect(shouldProcess(issue)).toBe(true);
  });
});

describe("isTestSweepFinding", () => {
  it("true for test-sweep-failure label", () => {
    expect(
      isTestSweepFinding({ number: 1, labels: ["P2", "test-sweep-failure"], comments: [] }),
    ).toBe(true);
  });

  it("true for test-sweep-report label", () => {
    expect(isTestSweepFinding({ number: 1, labels: ["test-sweep-report"], comments: [] })).toBe(
      true,
    );
  });

  it("false when neither label is present", () => {
    expect(isTestSweepFinding({ number: 1, labels: ["bug", "P2"], comments: [] })).toBe(false);
    expect(isTestSweepFinding({ number: 1, comments: [] })).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Fixture-driven golden scenarios
// ---------------------------------------------------------------------------
describe("shouldProcess — golden fixtures", async () => {
  const fixtures = await loadFixtures();

  for (const { name, fixture } of fixtures) {
    it(`fixture ${name}: step2_keep=${fixture.expected.step2_keep} — ${fixture.expected.reason}`, () => {
      const issue = fixtureToIssue(fixture);
      const result = shouldProcess(issue);
      expect(result).toBe(fixture.expected.step2_keep);
    });
  }
});

// ---------------------------------------------------------------------------
// Forbidden action assertions
// ---------------------------------------------------------------------------
describe("forbidden_actions", async () => {
  const fixtures = await loadFixtures();

  it("every fixture has a forbidden_actions array (schema guard)", () => {
    for (const { name, fixture } of fixtures) {
      expect(
        Array.isArray(fixture.forbidden_actions),
        `fixture ${name}: forbidden_actions must be an array`,
      ).toBe(true);
    }
  });

  it("fixture 1025 must forbid pr-merge (never auto-merge a PR)", () => {
    const f = fixtures.find(({ name }) => name.startsWith("1025-"));
    expect(f, "1025 fixture not found").toBeDefined();
    const forbidden = f!.fixture.forbidden_actions;
    // Both the gh CLI command AND the MCP tool name must be forbidden
    expect(forbidden.some((a) => a.includes("pr merge") || a.includes("merge_pull_request"))).toBe(
      true,
    );
  });

  it("fixture 535 must forbid git rm of the file (false-premise trap)", () => {
    const f = fixtures.find(({ name }) => name.startsWith("535-"));
    expect(f, "535 fixture not found").toBeDefined();
    const forbidden = f!.fixture.forbidden_actions;
    expect(forbidden.some((a) => a.includes("git rm") && a.includes("sample.test.ts"))).toBe(true);
  });

  it("fixtures with step2_keep=false have no forbidden_actions (not reached)", () => {
    for (const { name, fixture } of fixtures) {
      if (!fixture.expected.step2_keep) {
        expect(
          fixture.forbidden_actions.length,
          `fixture ${name}: step2_keep=false should have no forbidden_actions`,
        ).toBe(0);
      }
    }
  });
});

// ---------------------------------------------------------------------------
// extractSweepTraces
// ---------------------------------------------------------------------------
describe("extractSweepTraces", () => {
  it("extracts a well-formed trace from a comment body", () => {
    const body =
      '> 🤖 AI Agent\n<!-- sweep-trace: {"ver":1,"issue":533,"gate":"step2","val":"non-terminal","run":"2026-07-10T12:00:00Z"} -->';
    const traces = extractSweepTraces(body);
    expect(traces.length).toBe(1);
    expect(traces[0]).toMatchObject({ ver: 1, issue: 533, gate: "step2", val: "non-terminal" });
  });

  it("extracts multiple traces from a single body", () => {
    const body = [
      '<!-- sweep-trace: {"ver":1,"gate":"step1","val":"keep","run":"2026-07-10T12:00:00Z"} -->',
      '<!-- sweep-trace: {"ver":1,"gate":"step2","val":"human-reply","run":"2026-07-10T12:00:01Z"} -->',
    ].join("\n");
    const traces = extractSweepTraces(body);
    expect(traces.length).toBe(2);
    expect(traces.map((t) => t.gate)).toEqual(["step1", "step2"]);
  });

  it("returns an empty array when no trace is present", () => {
    expect(extractSweepTraces("> 🤖 AI Agent\nNo trace here.")).toEqual([]);
  });

  it("skips malformed JSON gracefully", () => {
    const body = "<!-- sweep-trace: {not valid json} -->";
    expect(extractSweepTraces(body)).toEqual([]);
  });

  it("handles extra whitespace around the JSON", () => {
    const body = '<!--  sweep-trace:  {"ver":1,"gate":"test","val":"ok","run":"r"}  -->';
    const traces = extractSweepTraces(body);
    expect(traces.length).toBe(1);
  });
});

/**
 * Regressions from the first live arc sweep (fleet dry-run smoke). Each case below
 * is a REAL misclassification observed against arc's open issues, not a hypothetical.
 */
describe("live-sweep regressions", () => {
  it("a deferral word inside a CODE BLOCK is not a deferral (`cancel-in-progress: false`, #1698)", () => {
    const body = [
      "> 🤖 AI Agent — issue-sweep",
      "分析完成。CI 并发配置如下:",
      "```yaml",
      "concurrency:",
      "  cancel-in-progress: false",
      "```",
      "结论已给出。",
    ].join("\n");
    expect(isNonTerminalAiComment(body)).toBe(false); // `in-progress` only lives in the fence
  });

  it("prose about Actions queueing is not a 排队中 freeze marker (#1698)", () => {
    const body = "> 🤖 AI Agent\n该 workflow 会在 runner 上排队等待执行,属正常现象,结论如上。";
    expect(isNonTerminalAiComment(body)).toBe(false); // bare 排队 no longer matches
  });

  it("a TERMINAL security escalation is NOT re-picked because its prose says 不在本轮自动修 (#1521)", () => {
    const body =
      "> 🤖 AI Agent\n🔴 security-sensitive:证据不充分,不在本轮自动修,交人类判断。" + TRACE;
    expect(isTerminalAiComment(body)).toBe(true);
    expect(shouldProcess({ number: 1521, comments: [{ body }] })).toBe(false); // terminal wins
  });

  it("terminal beats an incidental deferral word (ordering was inverted)", () => {
    const body = "> 🤖 AI Agent\n已开 PR #1699 修复;其余 TODO 留待后续。" + TRACE;
    expect(shouldProcess({ number: 1, comments: [{ body }] })).toBe(false);
  });

  it("the presence board's `> 📡` heartbeat is agent-authored, not fresh human input (#1361)", () => {
    const body = "> 📡 presence heartbeat — issue-sweep hourly · no-op";
    expect(isAiAgentComment(body)).toBe(true);
    expect(shouldProcess({ number: 1361, comments: [{ body }] })).toBe(false);
  });

  it("an identity-line suffix ALONE is no longer agent — a human's local comment looks identical (arc#1722)", () => {
    // #1347's identity line is emitted by scripts/agent-identity.sh, which BOTH humans and
    // agents run — so it cannot discriminate. A real autonomous cloud comment is caught at
    // runtime by its Bot author (claude[bot]); a local one by its sweep-trace.
    expect(isAiAgentComment("报告正文。\n\n@ vm · runner:robert · skills@a2298a3b")).toBe(false);
    expect(isAiAgentComment("报告正文。\n\n@ vm · runner:robert · skills@a2298a3b" + TRACE)).toBe(
      true,
    );
  });

  it("an HTML-ESCAPED marker is still extracted (#1278 double-escape, seen live)", () => {
    const body = '&lt;!-- sweep-trace: {"ver":1,"gate":"g","val":"v","run":"r"} --&gt;';
    expect(extractSweepTraces(body).length).toBe(1);
  });

  it("a real human comment is still kept (no false agent-marker)", () => {
    expect(isAiAgentComment("这个我看了,按方案 B 来吧。")).toBe(false);
    expect(shouldProcess({ number: 2, comments: [{ body: "按方案 B 来吧。" }] })).toBe(true);
  });
});
