/**
 * issue-graph 共享工具：REST-only 的 gh 封装。
 *
 * 为什么不用 GraphQL / --paginate：cloud routine 环境的出站代理只放行 gh 的
 * REST 调用（GraphQL 报 403 "not enabled for this session"），且 --paginate
 * 对 issues 端点会被代理改写 Link header 触发 numeric-ID 错误（见根
 * CLAUDE.md「按需安装 CLI 依赖」节）。所以：全 REST + 手动 page=N 循环。
 */

export interface GhResult {
  ok: boolean;
  code: number;
  stdout: string;
  stderr: string;
}

export function gh(args: string[]): GhResult {
  const p = Bun.spawnSync(["gh", ...args], { stdout: "pipe", stderr: "pipe" });
  return {
    ok: p.exitCode === 0,
    code: p.exitCode ?? -1,
    stdout: p.stdout.toString(),
    stderr: p.stderr.toString(),
  };
}

/** GET/POST 等 REST 调用；非 2xx 抛错（带 stderr 摘要）。 */
export function api(path: string, extra: string[] = []): any {
  const r = gh(["api", path, ...extra]);
  if (!r.ok) throw new Error(`gh api ${path} failed (${r.code}): ${r.stderr.slice(0, 400)}`);
  return r.stdout.trim() ? JSON.parse(r.stdout) : null;
}

/** 同 api()，但把 HTTP 错误作为值返回而不是抛出（幂等写入要辨认 422 等）。 */
export function apiRaw(path: string, extra: string[] = []): GhResult {
  return gh(["api", path, ...extra]);
}

/** 手动分页 GET：循环 page=1,2,3… 直到返回空页。 */
export function apiPaged(pathWithQuery: string, maxPages = 20): any[] {
  const sep = pathWithQuery.includes("?") ? "&" : "?";
  const out: any[] = [];
  for (let page = 1; page <= maxPages; page++) {
    const batch = api(`${pathWithQuery}${sep}per_page=100&page=${page}`);
    const items = Array.isArray(batch) ? batch : (batch?.items ?? []);
    out.push(...items);
    if (items.length < 100) break;
  }
  return out;
}

/**
 * 从 git remote URL 提取 owner/repo；非 github.com 或解析不出返回 null。
 *
 * 兜底识别 `.../git/<owner>/<repo>` 路径形态——某些 Claude Code 云端会话的出站
 * git 代理（本地 git-proxy daemon，如 `http://local_proxy@127.0.0.1:<port>/git/<owner>/<repo>`）
 * 把 origin 重写成这个形态而非真实 github.com host，`gh` 的 `{owner}/{repo}`
 * 占位符解析因此认不出「known GitHub host」而失败（issue #745 verification
 * comment.ts 的 --comment 全部失败即因于此）。只匹配字面 `/git/` 路径段，
 * 不放宽成任意 host 的「最后两段」——否则会让 gitlab.com 等非 github 远程
 * 误判为可用（见 lib.test.ts "non-github remote returns null"）。
 */
export function parseOwnerRepoFromGitUrl(url: string): string | null {
  const trimmed = url.trim();
  const github = trimmed.match(/github\.com[/:]([\w.-]+)\/([\w.-]+?)(?:\.git)?\/?$/);
  if (github) return `${github[1]}/${github[2]}`;
  const proxy = trimmed.match(/\/git\/([\w.-]+)\/([\w.-]+?)(?:\.git)?\/?$/);
  return proxy ? `${proxy[1]}/${proxy[2]}` : null;
}

export function resolveRepo(explicit?: string): string {
  if (explicit) return explicit;
  if (process.env.ISSUE_GRAPH_REPO) return process.env.ISSUE_GRAPH_REPO;
  // 先走纯本地的 git remote（零网络）——`gh repo view` 是 GraphQL，
  // cloud-routine 代理必拒（见文件头注释），只留作最后的兜底。
  const remote = Bun.spawnSync(["git", "remote", "get-url", "origin"], {
    stdout: "pipe",
    stderr: "pipe",
  });
  if (remote.exitCode === 0) {
    const parsed = parseOwnerRepoFromGitUrl(remote.stdout.toString());
    if (parsed) return parsed;
  }
  const r = gh(["repo", "view", "--json", "nameWithOwner", "--jq", ".nameWithOwner"]);
  if (!r.ok) throw new Error("无法确定 repo：不在 git repo 内且未传 --repo / ISSUE_GRAPH_REPO");
  return r.stdout.trim();
}

/** 简单字符串 hash（顺序随机化用，不求密码学强度）。 */
export function strHash(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0;
  return Math.abs(h);
}

/**
 * 按 hostname 旋转数组起点：成员资格确定性、处理顺序机器间错峰，
 * 让多机同分钟起跑时锁竞争从"必然"变"罕见"（#1308 并发设计第 2 条）。
 */
export function hostRotate<T>(arr: T[]): T[] {
  if (arr.length <= 1) return arr;
  const host = process.env.HOSTNAME ?? Bun.spawnSync(["hostname"]).stdout.toString().trim();
  const k = strHash(host) % arr.length;
  return [...arr.slice(k), ...arr.slice(0, k)];
}

/**
 * 评论是否 agent 发出——判据与 issue-sweep SKILL.md Step 2 对齐(#1805):
 * 前 ~3 行含 🤖,或以 `_Generated by [Claude Code]` footer 结尾,或携带
 * `<!-- sweep-trace: ... -->` 标记。窄判据(仅字面 `🤖 AI Agent`)会漏判
 * 身份行格式的评论(`@ <hostname> · runner:... \n\n## 父级 rollup 核对...`,
 * 无 🤖 emoji),导致 #378 这类已复核的 rollup candidate 被反复重新核对。
 */
export function isAgentAuthored(body: string): boolean {
  const head = body.split("\n").slice(0, 3).join("\n");
  if (/🤖/.test(head)) return true;
  if (/_Generated by \[Claude Code\]/.test(body)) return true;
  if (/<!--\s*sweep-trace:/.test(body)) return true;
  return false;
}

/**
 * 父级 rollup candidate 是否「已复核、无新信号」——避免同一 partial-rollup
 * issue 被每轮 sweep 反复重新核对(#378 实测:15 条重复"父级 rollup 核对"
 * 评论,跨 3 台机器、近 3 周,结论从未变化,纯浪费)。
 *
 * 判定:最后一条评论是 agent 发的 rollup 核对结论(标题含"父级 rollup"或
 * "Rollup 核对"),且它的时间晚于所有已知子 issue 的关闭时间——即上次核对
 * 之后没有任何子 issue 状态变化,再核一次只会得到相同结论。子 issue 关闭
 * 时间未知(maxChildClosedAt 为 null)时保守按"已复核"处理,不空转。
 */
export function isRollupAlreadyReviewed(
  lastCommentBody: string | null,
  lastCommentCreatedAt: string | null,
  maxChildClosedAt: string | null,
): boolean {
  if (!lastCommentBody || !lastCommentCreatedAt) return false;
  const isRollupVerdict = /父级 rollup|Rollup 核对/.test(lastCommentBody);
  if (!isAgentAuthored(lastCommentBody) || !isRollupVerdict) return false;
  if (!maxChildClosedAt) return true;
  return lastCommentCreatedAt > maxChildClosedAt;
}

export function parseArgs(argv: string[]): Map<string, string | boolean> {
  const m = new Map<string, string | boolean>();
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (!a.startsWith("--")) continue;
    const key = a.slice(2);
    const next = argv[i + 1];
    if (next !== undefined && !next.startsWith("--")) {
      m.set(key, next);
      i++;
    } else {
      m.set(key, true);
    }
  }
  return m;
}
